<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone</name>
   <tag></tag>
   <elementGuidId>30c4ce4f-4467-41cc-bd4c-2b621900095b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noTlp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noTlp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39cc2ca8-5850-4b46-a9e5-a5a79da7b86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>60434058-2759-4684-86cd-43063f0caac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>126579e6-d164-4ad8-94a3-1df3bf95e15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>bd038ac7-4fbe-4793-abab-a9f840dc2e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noTlp</value>
      <webElementGuid>432b8428-1c30-4558-9c35-8b330bc04d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Tlp</value>
      <webElementGuid>95265a1e-6923-477c-97d8-1c11f06c98a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noTlp&quot;)</value>
      <webElementGuid>bde50ec2-d652-47d8-928e-6b8b2320cf34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noTlp']</value>
      <webElementGuid>a899e83f-6515-4c7e-ac36-a50b94fc1788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[3]/div/input</value>
      <webElementGuid>3440a01c-4a57-4c0d-8609-20d3d2400e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>7c2ed1a1-b869-4c13-acf0-1bcfbcc17c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phone' and @type = 'text' and @id = 'noTlp' and @placeholder = 'No Tlp']</value>
      <webElementGuid>932d1e41-9dc4-4a5f-b0ea-f9e0fb9dc370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
