<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_phone is a required field</name>
   <tag></tag>
   <elementGuidId>d9ee728c-ff60-4d66-a9e6-353916c08d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-sm.text-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3e5822b-e463-47c8-8c14-45e931cdfd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-error</value>
      <webElementGuid>29250ac0-f91e-49ba-b823-46e42fed8ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>phone is a required field</value>
      <webElementGuid>3cb47f85-dc18-4eb6-a8fc-e0e23718116d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/span[@class=&quot;text-sm text-error&quot;]</value>
      <webElementGuid>d827d193-69fe-4e85-b9d5-1ea525df7348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[3]/div/span</value>
      <webElementGuid>9b992262-7218-48bb-b3ba-508e00db66b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[1]</value>
      <webElementGuid>93926857-82d3-43ee-9e21-d9ce2fc648d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[1]</value>
      <webElementGuid>b8539d63-ed2a-4bf6-a499-087d5d8a2170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='phone is a required field']/parent::*</value>
      <webElementGuid>da597728-a332-46c7-a604-921ebeff9c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>2e090a4a-9348-4185-aceb-3b7af0212881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'phone is a required field' or . = 'phone is a required field')]</value>
      <webElementGuid>bf3e0a55-27a4-432d-8c4e-679179aa2f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
