<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__buildingName</name>
   <tag></tag>
   <elementGuidId>0c049c70-2f5d-4f02-b456-b795ee0c9811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameBuilding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameBuilding']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8f13a39-ba28-4fde-ae39-0d65f3617de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingName</value>
      <webElementGuid>8be7091d-65d8-4b27-9297-843104c1fa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7871ac2b-f0d5-4601-aba0-e317b113262c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>1559d444-b45c-4791-aa91-2242c7b3c137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameBuilding</value>
      <webElementGuid>9b33e07b-a199-4ada-a4a8-f283dad65d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: Melati Meeting Room</value>
      <webElementGuid>054f89f3-321f-4440-b752-4c1051589c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Building Update</value>
      <webElementGuid>2f068d3a-f857-413d-bbd4-b845e1f68edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/input[@id=&quot;nameBuilding&quot;]</value>
      <webElementGuid>781ba91c-9397-49f6-a3ae-c7c49f45e3c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameBuilding']</value>
      <webElementGuid>0d3bd16e-279a-44a1-8972-2a0cdb67c7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[2]/div/input</value>
      <webElementGuid>cb29939e-4dcd-4a5c-b44c-b3786b10f09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c4c12f19-2307-4a12-a5a1-81d5eea54c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'buildingName' and @type = 'text' and @id = 'nameBuilding' and @placeholder = 'Ex: Melati Meeting Room']</value>
      <webElementGuid>afde3f86-ada4-4e86-9942-146a61968ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
