<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EmailPasswordRemember MeLog In</name>
   <tag></tag>
   <elementGuidId>d9244b1a-158f-47dc-bf77-bcadb169e04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.d-flex.flex-column.bg-indigo-100.justify-content-center.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a1f64d9-877f-4c9b-8a90-4c53fc2f171e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col d-flex flex-column bg-indigo-100 justify-content-center align-items-center</value>
      <webElementGuid>f0fbea8f-4b48-4b6d-9853-a609f9ef9898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailPasswordRemember MeLog In</value>
      <webElementGuid>4ee95d16-75af-47f5-aaf8-706299188bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;row vh-100&quot;]/div[@class=&quot;col d-flex flex-column bg-indigo-100 justify-content-center align-items-center&quot;]</value>
      <webElementGuid>a2f6b5a0-b26b-4965-96b1-241203d29dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]</value>
      <webElementGuid>40f6e447-46e8-4597-8fed-7eedc396ac36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>ca9943b3-0f13-4b8f-b623-bd7a57798747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EmailPasswordRemember MeLog In' or . = 'EmailPasswordRemember MeLog In')]</value>
      <webElementGuid>ae3202bb-e6d6-4866-bcb4-cd9cfb69adcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
