<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Photo Profile images is a required fie_28defe</name>
   <tag></tag>
   <elementGuidId>efe4f182-f69e-4529-86e3-f88a2147395f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='#']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>520a71ee-b743-450d-a7b3-26213ac65b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>376a0cc8-3b5e-45fe-af7b-f53f2d195223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photo Profile *images is a required fieldEmail *Nomor Tlp *Name *Password *Confirm Password *CancelAdd Customer</value>
      <webElementGuid>9b98b92d-1793-4155-83a7-c5059de4f237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]</value>
      <webElementGuid>6a74d3f8-9114-45d5-ad56-753c18035731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='#']</value>
      <webElementGuid>e91686ba-d01c-4357-9468-087301a474fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form</value>
      <webElementGuid>591e25c6-9f7d-48ad-817d-e7029a29a6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='add-customer'])[1]/following::form[1]</value>
      <webElementGuid>1da12c28-7baf-4ef3-8d5c-b3b3e2a5d231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/following::form[1]</value>
      <webElementGuid>72752fcf-458b-413b-bf25-6d05e8222038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form</value>
      <webElementGuid>4dc524ed-8d83-4a71-be60-1c7ebf1670c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Photo Profile *images is a required fieldEmail *Nomor Tlp *Name *Password *Confirm Password *CancelAdd Customer' or . = 'Photo Profile *images is a required fieldEmail *Nomor Tlp *Name *Password *Confirm Password *CancelAdd Customer')]</value>
      <webElementGuid>b06fbdbd-90ce-4b9a-8645-8808c443a576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
