<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Photo Profile</name>
   <tag></tag>
   <elementGuidId>10fb23b9-2835-45df-868c-bbd924c4e0f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.img-upload.d-flex.flex-column.align-items-center.text-gray-dark.text-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b43d982a-aed8-46b7-ba7d-329f9610f7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b93bcac3-b365-4abb-9c85-973e76d88cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-upload d-flex flex-column align-items-center text-gray-dark text-sm</value>
      <webElementGuid>cc14aeb4-0f7b-4d33-9dcf-6cd7ab0ef1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photo Profile</value>
      <webElementGuid>f0f8c570-0ca9-420b-8ec8-f5db93be01a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/label[@class=&quot;img-upload d-flex flex-column align-items-center text-gray-dark text-sm&quot;]</value>
      <webElementGuid>e36065fa-2c3d-41ce-ae6c-90b2967e71dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div/div/div/label</value>
      <webElementGuid>9a3b86be-fb9a-45f8-a9a0-b33321a833c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>69c223de-4a01-4782-bbfb-575bc2a87aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label</value>
      <webElementGuid>02d04463-ee8e-4d5c-a8b7-cad40f9a2c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Photo Profile' or . = 'Photo Profile')]</value>
      <webElementGuid>d4ecd52a-ecd1-4798-a011-92477a832a0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
