<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nav-link__admin User ProfileUsers</name>
   <tag></tag>
   <elementGuidId>bb4acaf9-7368-48e3-86d3-6ea869d6ce0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.accordion-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd7fd8c8-3d90-47c2-8b61-f81a1d5ef90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button</value>
      <webElementGuid>eade7813-4935-47c2-8a27-f35cbb64b67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>254b7827-1566-4ebe-90b2-bd146b30ecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>7b036181-5d0c-468a-9729-bdd4ae6d7d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#flush-collapseOne</value>
      <webElementGuid>0d45480b-5dbd-4fb5-9559-1999e5bff0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04ccf449-6423-4575-a78e-7c19f32e9d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flush-collapseOne</value>
      <webElementGuid>85dbd2cc-9e65-4d47-ad11-785b1f8040bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nav-link__admin User ProfileUsers</value>
      <webElementGuid>fe9c7360-147a-45f0-aebd-f9d0d699d4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flush-headingOne&quot;)/button[@class=&quot;accordion-button&quot;]</value>
      <webElementGuid>39502d8a-8921-4884-8e86-2b17d8cc7891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>9b52993d-8394-4fd9-a18b-9ec9fa636a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='flush-headingOne']/button</value>
      <webElementGuid>6b78c61e-9044-47ea-864b-875a454ffbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservations'])[1]/following::button[1]</value>
      <webElementGuid>11de6f35-b499-4022-83bc-da1b0896176a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buildings'])[1]/following::button[1]</value>
      <webElementGuid>8faf1025-67cb-4bdd-8d3a-0c8f482da871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[1]/preceding::button[1]</value>
      <webElementGuid>6e343c82-0c6e-4f27-a9c4-1dac06e1cca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>38998e69-6c48-4452-97ce-f019e4fc7e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'nav-link__admin User ProfileUsers' or . = 'nav-link__admin User ProfileUsers')]</value>
      <webElementGuid>c8a4e2f1-8f35-410d-9c25-50ff31db040a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
