<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Photo Profile</name>
   <tag></tag>
   <elementGuidId>3f775b44-edba-496e-909e-5ab474e35420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.img-upload.d-flex.flex-column.align-items-center.text-gray-dark.text-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b9648ef9-8cc9-4a06-bc0e-0911356cea10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>394a13ac-87f7-46bf-87f6-feaa6215af84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-upload d-flex flex-column align-items-center text-gray-dark text-sm</value>
      <webElementGuid>0f095583-e11e-44a0-92d5-2cfcbd2a8921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photo Profile</value>
      <webElementGuid>4fe57e3c-f932-4c72-b0a5-8c71b0ade8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/label[@class=&quot;img-upload d-flex flex-column align-items-center text-gray-dark text-sm&quot;]</value>
      <webElementGuid>9c0ea387-3549-45e0-8e65-3457192a05b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div/div/div/label</value>
      <webElementGuid>6fc106d9-5487-42b2-a8c0-cf5c4828ad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>28671c87-ef52-43e8-b492-3d83c5162463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label</value>
      <webElementGuid>617859bc-ca7d-4150-a0b0-4315c1b53150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Photo Profile' or . = 'Photo Profile')]</value>
      <webElementGuid>87c6c253-c130-4304-b368-6e3b87eb4f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
