<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Emailemail is a required fieldPasswordR_050cbc</name>
   <tag></tag>
   <elementGuidId>e8a700f7-84c1-4186-8df6-9798dc56a885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.d-flex.flex-column.bg-indigo-100.justify-content-center.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0e6a2fd-3bc4-4549-9111-23c7f64f49df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col d-flex flex-column bg-indigo-100 justify-content-center align-items-center</value>
      <webElementGuid>d8a07b56-60f2-4359-ad70-e608b74077fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emailemail is a required fieldPasswordRemember MeLog In</value>
      <webElementGuid>698a2935-9ecf-4cbf-987d-f0d0154da049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;row vh-100&quot;]/div[@class=&quot;col d-flex flex-column bg-indigo-100 justify-content-center align-items-center&quot;]</value>
      <webElementGuid>afea7c63-ebe2-480d-a4a1-b11b7ed80dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]</value>
      <webElementGuid>742cb0ff-db25-4c68-946a-39bdf25264ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>9331a556-96f8-4137-96ec-e89abc780d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Emailemail is a required fieldPasswordRemember MeLog In' or . = 'Emailemail is a required fieldPasswordRemember MeLog In')]</value>
      <webElementGuid>0535c48d-c8ac-4000-a776-bf6742c0e303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
