<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Update</name>
   <tag></tag>
   <elementGuidId>adcf0a0d-6fd4-49df-8a13-d2ad3011c391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div/table/tbody/tr[2]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>961b1617-59a3-4db9-b248-59c5d3d5551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn bg-success text-sm me-4 text-white px-4 py-2</value>
      <webElementGuid>41dff7ca-1529-448d-a741-5b197280c124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/customers/edit-customer/787a95ed-afd2-4030-a5f8-d164942be65a</value>
      <webElementGuid>df4a4c25-6915-49c7-83a9-4618d5f33282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>b186435a-f6ab-4e3e-b459-34125bbf90e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[4]/a[@class=&quot;btn bg-success text-sm me-4 text-white px-4 py-2&quot;]</value>
      <webElementGuid>cea87b80-8f7e-4967-a2c6-9325dc24d2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div/table/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>a9155312-6f4a-4222-a8f4-3ffd9a0f0dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Update')])[2]</value>
      <webElementGuid>826d45fb-76e5-4530-8e76-96f32dca595d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin123@mail.fortyfourvisual.com'])[1]/following::a[1]</value>
      <webElementGuid>340ecf69-6463-4948-a273-bd2a5113f710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ronaa'])[1]/following::a[1]</value>
      <webElementGuid>34eb5c42-e7cc-4663-8ae5-41a901bef62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::a[1]</value>
      <webElementGuid>294a3610-021b-4a6c-b9f2-cfc774ab9226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='indra'])[1]/preceding::a[1]</value>
      <webElementGuid>c156c5ba-b055-44f0-b4df-5df57249b8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/customers/edit-customer/787a95ed-afd2-4030-a5f8-d164942be65a')]</value>
      <webElementGuid>f27d8b36-ab8c-4864-90b2-65b675714a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>aedb421c-ef1e-40e5-b8a4-9777f8d3c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/customers/edit-customer/787a95ed-afd2-4030-a5f8-d164942be65a' and (text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>5440aa17-f63d-4b68-bfe3-11b5bf3ba81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
