<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2</name>
   <tag></tag>
   <elementGuidId>b2927a21-20af-425c-ad43-f1fc547039d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.page-link.null</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div[2]/nav/ul/li[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d964103e-6f19-4b96-91af-db5f7de2a3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link null</value>
      <webElementGuid>9c2dfef5-8aef-4342-985a-fb35b12a4cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>de511440-81a0-4ae4-a2a2-eea01be8a47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/div[@class=&quot;card&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/nav[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item&quot;]/div[@class=&quot;page-link null&quot;]</value>
      <webElementGuid>9e219f0b-d8fa-42ef-9270-d14e254eda4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div[2]/nav/ul/li[3]/div</value>
      <webElementGuid>2d61380f-30a6-48c9-9661-4241837d0531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::div[2]</value>
      <webElementGuid>f8f935a7-93a2-4978-aa19-8ee1ad386d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canceled'])[4]/following::div[4]</value>
      <webElementGuid>6c167a0b-7113-4c14-8f1d-d51ceadd661f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::div[1]</value>
      <webElementGuid>129ffc38-4f5c-4a27-8b1b-7018287b8092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>38740918-ed7b-4ed3-a287-89da7e55c8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2' or . = '2')]</value>
      <webElementGuid>d07df309-5093-4235-bbe8-d4cb7c98ff40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
