<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Building Up 1A_img-building 4 h-4 m-2</name>
   <tag></tag>
   <elementGuidId>f710bebc-9c90-44ac-8bfc-edd4bd227f2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-building.4.h-4.m-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div/table/tbody/tr/td/h1/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2fe5430d-6084-44af-86b6-a1241f6db201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ik.imagekit.io/fortyfour/default-image.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1651795109157</value>
      <webElementGuid>eab9523f-ae57-4637-8b3e-f583bc35a795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>4a598de5-a30d-4b21-8143-4100a94477e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-building 4 h-4 m-2</value>
      <webElementGuid>5e94826a-366c-441e-99d9-72381c3d79f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[1]/h1[@class=&quot;text-primary-dark text-sm&quot;]/img[@class=&quot;img-building 4 h-4 m-2&quot;]</value>
      <webElementGuid>6c3958b8-f5fb-4a18-b894-1e76f25dbc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/div[3]/div/table/tbody/tr/td/h1/img</value>
      <webElementGuid>0aa9c348-9ff7-4005-95d5-a47d340e7fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='name']</value>
      <webElementGuid>045c59f5-6ace-4bc3-9289-b7dd13a248de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/img</value>
      <webElementGuid>a6c43328-1752-44cf-bab0-5cf153edc6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ik.imagekit.io/fortyfour/default-image.jpg?ik-sdk-version=javascript-1.4.3&amp;updatedAt=1651795109157' and @alt = 'name']</value>
      <webElementGuid>b199c04f-b17c-475e-9e17-7ec7857a342b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
