<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_option Cilandak focused, 3 of 10. 10 re_db0f1e</name>
   <tag></tag>
   <elementGuidId>45920ac1-4729-40b0-a056-94a399f4a067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='nameBuilding'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c82086f0-df70-4eb9-85e9-7b1da4704293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-select__control css-b62m3t-container</value>
      <webElementGuid>56639d96-24b9-4874-a77c-b5adf89c8de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameBuilding</value>
      <webElementGuid>ba03bb45-961a-4532-8848-a8026b5d8fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>option Cilandak focused, 3 of 10. 10 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select One...JagakarsaPasar MingguCilandakPesanggrahanKebayoran LamaKebayoran BaruMampang PrapatanPancoranTebetSetia Budi</value>
      <webElementGuid>3c0ce8d3-8e97-44d5-ac07-1bcaf312dca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/div[@id=&quot;nameBuilding&quot;]</value>
      <webElementGuid>c1d87b95-3717-4070-876c-3cf7bd526899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='nameBuilding'])[2]</value>
      <webElementGuid>c7105e0d-f4db-4c54-ad27-50ea44767d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[4]/div/div</value>
      <webElementGuid>eb7b13d8-5f9f-4884-b4e2-62d9803466b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[2]</value>
      <webElementGuid>075fb09f-1c9e-4924-bc87-06f11eee7fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>295e61cd-ace1-4a0b-b9ed-01197746a11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nameBuilding' and (text() = 'option Cilandak focused, 3 of 10. 10 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select One...JagakarsaPasar MingguCilandakPesanggrahanKebayoran LamaKebayoran BaruMampang PrapatanPancoranTebetSetia Budi' or . = 'option Cilandak focused, 3 of 10. 10 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.Select One...JagakarsaPasar MingguCilandakPesanggrahanKebayoran LamaKebayoran BaruMampang PrapatanPancoranTebetSetia Budi')]</value>
      <webElementGuid>2167a409-b506-4fdc-9aab-bb91bc345239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
