<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fasilitas</name>
   <tag></tag>
   <elementGuidId>66862f36-6ce1-4e90-8085-10157c0fe030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fasilitas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fasilitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f478fd4-8729-43aa-8d61-baf61de16778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fbfa123-8840-4af8-a8e1-07af8f27312c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>0a6baa0e-02e5-4d11-a591-303993d83a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fasilitas</value>
      <webElementGuid>4853371c-6b5f-41c6-b9a0-dadb8a1fb433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Facility</value>
      <webElementGuid>d09a4089-8c56-42bc-9ae9-eea1c7a491a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;d-flex w-100 mb-3&quot;]/input[@id=&quot;fasilitas&quot;]</value>
      <webElementGuid>65894372-b23f-4f4a-853e-5ffd9760c808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fasilitas']</value>
      <webElementGuid>01ea85fb-bf31-4528-a8bd-4c58d9343653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[7]/div/div/input</value>
      <webElementGuid>3fae55ad-d706-4988-b258-82d602851f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>2f4df50c-ed2b-4a16-ae77-d9d8586f4411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fasilitas' and @placeholder = 'Facility']</value>
      <webElementGuid>add94cf4-0f00-41de-8088-3e8e4f62fb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
