<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl.Tes</name>
   <tag></tag>
   <elementGuidId>aa8a7609-243a-45ca-8507-480144aed81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d5ab1347-0a0a-4ec4-9b20-f652cbd06a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>be37ee63-60c6-44d6-83a7-50fa0e00f14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>f4db739d-a5c7-4c33-8300-ac26aafdd281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: Jl Melati Raya no 23 RT 12 RW 2, Tebet</value>
      <webElementGuid>b07e0f3f-3e71-4c78-8023-564b227e72d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl.Tes</value>
      <webElementGuid>b0170477-9d65-4b9d-8558-9a061ccd229a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;flex-grow-1 h-full&quot;]/div[@class=&quot;p-3&quot;]/div[2]/form[1]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;col-9&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>a1bf5313-613d-4b55-81ea-897b9156781b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='address']</value>
      <webElementGuid>16175f54-0417-459b-bb01-35e9f9465de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div[2]/div/div[2]/form/div[5]/div/textarea</value>
      <webElementGuid>c5051a05-f6e6-48e3-9e87-0cad295bf30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>933873ad-0aac-4a2f-94ac-2a74662f16d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::textarea[1]</value>
      <webElementGuid>48166ccd-3d6c-4941-9cf7-1cc4a4d373fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl.Tes']/parent::*</value>
      <webElementGuid>cb9ca177-ef99-4de4-b8b7-7f737b400007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>18aad127-a4e8-49e6-85eb-6a4da19733ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'address' and @placeholder = 'Ex: Jl Melati Raya no 23 RT 12 RW 2, Tebet' and (text() = 'Jl.Tes' or . = 'Jl.Tes')]</value>
      <webElementGuid>c097244b-fbdf-4ebd-82b2-350fbdd764f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
